// src/frontend/src/app.tsx
import { useState } from 'preact/hooks';
import { useSocket } from './hooks/useSocket';
import { Layout } from './components/Layout';
import { OnboardingPage } from './pages/OnboardingPage';
import { DashboardPage } from './pages/DashboardPage';
import { ServerDetailsPage } from './pages/ServerDetailsPage';
import { PrerequisitesCheck } from './components/PrerequisitesCheck';
import { SettingsPage } from './pages/SettingsPage';
import { Modal } from './components/Modal';
import './index.css';

export function App() {
  const {
    config,
    socket,
    saveCredentials,
    createServer,
    updateServer,
    deleteServer,
    deployServer,
    deploying,
    logs,
    prerequisites,
    checkPrerequisites
  } = useSocket();

  const [activeTab, setActiveTab] = useState<'dashboard' | 'settings'>('dashboard');
  const [isAddServerModalOpen, setIsAddServerModalOpen] = useState(false);
  const [newServerName, setNewServerName] = useState('');
  const [newServerPath, setNewServerPath] = useState('');
  const [selectedServerId, setSelectedServerId] = useState<string | null>(null);

  const handleAddServer = () => {
    if (!newServerName || !newServerPath) return;
    createServer({
      name: newServerName,
      sourcePath: newServerPath,
      description: 'Added via Dashboard'
    });
    setIsAddServerModalOpen(false);
    setNewServerName('');
    setNewServerPath('');
  };

  if (!config.onboardingCompleted) {
    return (
      <OnboardingPage
        onComplete={(creds) => {
          saveCredentials(creds);
        }}
      />
    );
  }

  const selectedServer = config.servers.find(s => s.id === selectedServerId);

  return (
    <Layout activeTab={activeTab} onTabChange={(tab) => {
      setActiveTab(tab);
      setSelectedServerId(null);
    }}>
      {activeTab === 'dashboard' && !selectedServer && (
        <>
          <div className="mb-6">
            <PrerequisitesCheck 
              prerequisites={prerequisites} 
              onRefresh={checkPrerequisites}
            />
          </div>
          <DashboardPage
            servers={config.servers}
            onAddServer={() => setIsAddServerModalOpen(true)}
            onManageServer={(id) => setSelectedServerId(id)}
          />
        </>
      )}

      {activeTab === 'dashboard' && selectedServer && (
        <ServerDetailsPage
          server={selectedServer}
          onBack={() => setSelectedServerId(null)}
          onDeploy={(deployOnly) => deployServer(selectedServer.id, deployOnly)}
          onUpdate={updateServer}
          onDelete={deleteServer}
          isDeploying={deploying}
          logs={logs}
          socket={socket}
          projectId={config.credentials.googleProjectId}
        />
      )}

      {activeTab === 'settings' && (
        <SettingsPage
          config={config}
          onSaveCredentials={saveCredentials}
        />
      )}

      {/* Add Server Modal */}
      <Modal
        isOpen={isAddServerModalOpen}
        onClose={() => setIsAddServerModalOpen(false)}
        title="Add New Server"
      >
        <div className="space-y-4">
          <div className="space-y-2">
            <label className="text-xs font-medium text-muted-foreground">Server Name</label>
            <input
              type="text"
              value={newServerName}
              onInput={(e) => setNewServerName((e.target as HTMLInputElement).value)}
              placeholder="e.g. Weather Service"
              className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-ring"
              autoFocus
            />
          </div>
          <div className="space-y-2">
            <label className="text-xs font-medium text-muted-foreground">Project Path</label>
            <input
              type="text"
              value={newServerPath}
              onInput={(e) => setNewServerPath((e.target as HTMLInputElement).value)}
              placeholder="/absolute/path/to/project"
              className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-ring"
            />
            <p className="text-xs text-muted-foreground">
              Path to the directory containing your MCP server code.
            </p>
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <button
              onClick={() => setIsAddServerModalOpen(false)}
              className="rounded-md px-3 py-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleAddServer}
              disabled={!newServerName || !newServerPath}
              className="rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
            >
              Add Server
            </button>
          </div>
        </div>
      </Modal>
    </Layout>
  );
}

// src/frontend/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { socketStore } from './lib/stores/socketStore';
  import Layout from './lib/components/Layout.svelte';
  import Modal from './lib/components/Modal.svelte';
  import Input from './lib/components/Input.svelte';
  import Button from './lib/components/Button.svelte';
  import OnboardingPage from './lib/pages/OnboardingPage.svelte';
  import DashboardPage from './lib/pages/DashboardPage.svelte';
  import ServerDetailsPage from './lib/pages/ServerDetailsPage.svelte';
  import SettingsPage from './lib/pages/SettingsPage.svelte';

  // Destructure the nested stores from socketStore
  const configStore = socketStore.config;
  const logsStore = socketStore.logs;
  const deployingStore = socketStore.deploying;

  let activeTab: 'dashboard' | 'settings' = 'dashboard';
  let selectedServerId: string | null = null;
  let isAddServerModalOpen = false;
  let newServerName = '';
  let newServerPath = '';

  $: config = $configStore;
  $: logs = $logsStore;
  $: deploying = $deployingStore;
  $: selectedServer = config.servers.find(s => s.id === selectedServerId) || null;

  function coerceInputValue(e: unknown): string {
    const maybeAny = e as any;
    if (typeof maybeAny?.detail === 'string') return maybeAny.detail;
    const target = maybeAny?.target as HTMLInputElement | undefined | null;
    return typeof target?.value === 'string' ? target.value : '';
  }
  
  onMount(() => {
    socketStore.connect();
  });
  
  function handleAddServer() {
    if (newServerName && newServerPath) {
      socketStore.createServer({
        name: newServerName,
        sourcePath: newServerPath,
        description: 'Added via Dashboard'
      });
      isAddServerModalOpen = false;
      newServerName = '';
      newServerPath = '';
    }
  }
  
  function handleTabChange(tab: 'dashboard' | 'settings') {
    activeTab = tab;
    selectedServerId = null;
  }
  
  function handleManageServer(id: string) {
    selectedServerId = id;
  }
  
  function handleBack() {
    selectedServerId = null;
  }
  
  function handleDeploy(deployOnly: boolean) {
    if (selectedServerId) {
      socketStore.deployServer(selectedServerId, deployOnly);
    }
  }
  
  function handleDelete() {
    if (selectedServerId) {
      socketStore.deleteServer(selectedServerId);
      selectedServerId = null;
    }
  }
</script>

{#if !config.onboardingCompleted}
  <OnboardingPage />
{:else}
  <Layout {activeTab} onTabChange={handleTabChange}>
    {#if activeTab === 'dashboard' && !selectedServer}
      <DashboardPage
        servers={config.servers}
        onAddServer={() => isAddServerModalOpen = true}
        onManageServer={handleManageServer}
      />
    {:else if activeTab === 'dashboard' && selectedServer}
      <ServerDetailsPage
        server={selectedServer}
        onBack={handleBack}
        onDeploy={handleDeploy}
        onDelete={handleDelete}
        isDeploying={deploying}
        {logs}
        projectId={config.credentials.googleProjectId}
      />
    {:else if activeTab === 'settings'}
      <SettingsPage {config} />
    {/if}
  </Layout>
{/if}

<Modal
  isOpen={isAddServerModalOpen}
  title="Add New Server"
  on:close={() => isAddServerModalOpen = false}
>
  <div class="modal-form">
    <Input
      label="Server Name"
      placeholder="e.g. Weather Service"
      value={newServerName}
      on:input={(e) => newServerName = coerceInputValue(e)}
    />
    <Input
      label="Project Path"
      placeholder="/absolute/path/to/project"
      value={newServerPath}
      on:input={(e) => newServerPath = coerceInputValue(e)}
    />
    <p class="hint">Path to the directory containing your MCP server code.</p>
    <div class="modal-actions">
      <Button variant="secondary" on:click={() => isAddServerModalOpen = false}>
        Cancel
      </Button>
      <Button
        on:click={handleAddServer}
        disabled={!newServerName || !newServerPath}
      >
        Add Server
      </Button>
    </div>
  </div>
</Modal>

<style>
  .modal-form {
    display: flex;
    flex-direction: column;
    gap: 16px;
  }

  .hint {
    font-size: 12px;
    color: #9ca3af;
    margin: 0;
  }

  .modal-actions {
    display: flex;
    justify-content: flex-end;
    gap: 12px;
    margin-top: 8px;
  }
</style>
